'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4206
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace UF.Research.Authentication.Shibboleth

    Partial Public Class Settings

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''MessageCell control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessageCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnabled As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAutoCreateUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoCreateUsers As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAutoCreateUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoCreateUsers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSynchronizeRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSynchronizeRoles As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSynchronizeRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSynchronizeRoles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plLogoutPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogoutPage As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlLogoutPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLogoutPage As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLogoutPageError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLogoutPageError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLoginPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLoginPage As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlLoginPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLoginPage As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLoginPageError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoginPageError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSimulateLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSimulateLogin As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSimulateLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSimulateLogin As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtSimLoginTextFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSimLoginTextFile As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDelimiter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDelimiter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDelimiter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDelimiter As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
