'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UF.Research.Authentication.Shibboleth
    
    Partial Public Class ViewRoleMappings
        
        '''<summary>
        '''pnlAddShibHdrVar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddShibHdrVar As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''chkShibEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShibEnabled As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''chkShibSimulation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShibSimulation As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''lblShibUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShibUserName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnUpdateUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateUserName As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''RadGrid30 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadGrid30 As Global.Telerik.Web.UI.RadGrid
        
        '''<summary>
        '''btnUpdateShibHdrVar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateShibHdrVar As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''pnlAddTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddTask As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''RadGrid10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadGrid10 As Global.Telerik.Web.UI.RadGrid
        
        '''<summary>
        '''btnUpdateRoleMappings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateRoleMappings As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''pnlAddUserAttribute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddUserAttribute As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''RadGrid20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadGrid20 As Global.Telerik.Web.UI.RadGrid
        
        '''<summary>
        '''btnUpdateAttributes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateAttributes As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
